---
title: "Brian Norman Peña Calero's CV"
author: Brian Norman Peña Calero
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

if(!require("remotes")) install.packages("remotes")
if(!require("datadrivencv")) remotes::install_github("brianmsm/datadrivencv")

library(magrittr) # For the pipe
source("cv_printing_functions.r")
library(metathis)
```

```{r metathis, echo=FALSE}
meta() %>%
  meta_name("github-repo" = "brianmsm/cv-psicometrico") %>%
  meta_social(
    title = "CV Brian Norman Peña Calero",
    description = "Interés y formación abocado a la medición, evaluación, análisis y desarrollo de proyectos de investigación",
    url = "https://brianmsm.github.io/cv-psicometrico/",
    image = "https://brianmsm.github.io/cv-psicometrico/cover_cv.png",
    image_alt = "CV Brian Norman Peña Calero",
    og_type = "website",
    og_author = "Brian Norman Peña Calero",
    twitter_card_type = "summary_large_image"
  )
```

```{r, include=FALSE}
# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1j2K-ZpgNmcAVLz2NY6M_-2fZ1KLvC2uvOMG5qnrpBII",
  pdf_mode = params$pdf_mode
)
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("Puede ver una versión online del CV en [_brianmsm.github.io/cv-psicometrico_](https://brianmsm.github.io/cv-psicometrico/)")
} else {
  cat("[<i class='fas fa-download'></i> Descarga este CV en PDF](https://github.com/brianmsm/cv-psicometrico/raw/main/cv.pdf)")
}
```

Contacto {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Habilidades {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Hecho con el paquete R [**pagedown**](https://github.com/rstudio/pagedown). 

El código fuente se encuentra disponible [en github.com/brianmsm/cv-psicometrico](https://github.com/brianmsm/cv-psicometrico).

Última actualización: `r Sys.Date()`.



Main
================================================================================

Brian Norman Peña Calero {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Educación {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('educacion')
```



Experiencia {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('experiencia_investigacion')
```


Investigaciones {data-icon=book}
--------------------------------------------------------------------------------
::: aside
```{r}
CV %<>% print_text_block('articulos_conferencias_aside')
```
:::

```{r}
CV %<>% print_section('articulos_conferencias')
```

<br>

Capacitaciones {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('capacitaciones_aside')
```
:::

```{r}
CV %<>% print_section('capacitaciones')
```



